const rooms = [
  {
    _id: "67rdca3eeb7f6fgeed471815",
    name: "Studio",
    image: "some img",
    facilities: "TV, Wi-Fi, phone, shower",
    rate: 2.5,
  },
  {
    _id: "67rdca3eeb7f6fgeed471816",
    name: "Superior",
    image: "some img",
    facilities: "TV, Wi-Fi, phone, shower",
    rate: 2.5,
  },
  {
    _id: "67rdca3eeb7f6fgeed471817",
    name: "Double",
    image: "some img",
    facilities: "TV, Wi-Fi, phone, shower",
    rate: 2.5,
  },
  {
    _id: "67rdca3eeb7f6fgeed471818",
    name: "Superior sea view",
    image: "some img",
    facilities: "TV, Wi-Fi, phone, shower",
    rate: 2.5,
  },
  {
    _id: "67rdca3eeb7f6fgeed471819",
    name: "Family room",
    image: "some img",
    facilities: "TV, Wi-Fi, phone, shower",
    rate: 2.5,
  },
  {
    _id: "67rdca3eeb7f6fgeed471820",
    name: "Double sea view",
    image: "some img",
    facilities: "TV, Wi-Fi, phone, shower",
    rate: 2.5,
  },
  {
    _id: "67rdca3eeb7f6fgeed471821",
    name: "Standart sea view",
    image: "some img",
    facilities: "TV, Wi-Fi, phone, shower",
    rate: 2.5,
  },
  {
    _id: "67rdca3eeb7f6fgeed471822",
    name: "Superior sea-side view",
    image: "some img",
    facilities: "TV, Wi-Fi, phone, shower",
    rate: 2.5,
  },
  {
    _id: "67rdca3eeb7f6fgeed471823",
    name: "Standart sea-side view",
    image: "some img",
    facilities: "TV, Wi-Fi, phone, shower",
    rate: 2.5,
  },
  {
    _id: "67rdca3eeb7f6fgeed471824",
    name: "Double sea-side view",
    image: "some img",
    facilities: "TV, Wi-Fi, phone, shower",
    rate: 2.5,
  },
  {
    _id: "67rdca3eeb7f6fgeed47181f",
    name: "Studio-2",
    image: "some img",
    facilities: "TV, Wi-Fi, phone, shower",
    rate: 2.5,
  },
  {
    _id: "67rdca3eeb7f6fgeed47181r",
    name: "Studio-3",
    image: "some img",
    facilities: "TV, Wi-Fi, phone, shower",
    rate: 2.5,
  },
];
